Supply default cb value
I got this strange messages from gulp-git tag function:

```
/Users/floatdrop/sketchboard/node_modules/gulp-git/lib/tag.js:17
    if(err) cb(err);
            ^
TypeError: undefined is not a function
    at /Users/floatdrop/sketchboard/node_modules/gulp-git/lib/tag.js:17:13
```

Instead of this:

```
/Users/floatdrop/sketchboard/node_modules/gulp-git/lib/tag.js:6
  if(!cb) { cb = function (err) { if (err) throw err; } }
                                                 ^
Error: Command failed: fatal: tag 'v0.0.1' already exists
```